version = 1

exclude_patterns = [
  "bin/**",
  "**/node_modules/",
  "js/**/*.min.js"
]

test_patterns = [
  "tests/**",
  "**/*_test.go"
]

[[analyzers]]
name = "go"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true
