version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - goheader
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - whitespace
  settings:
    goheader:
      template-path: copyright.tmpl
    misspell:
      locale: US
    staticcheck:
      checks:
        - ST1019
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - .*_test\.go
      - .*test\.go
      - testing
      - src/jobservice/mgt/mock_manager.go
    rules:
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: common/const\.go
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: pkg/permission/types/namespace\.go
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: pkg/quota/types/resources\.go
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: common/utils/encrypt\.go
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: jobservice/api/router\.go
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: pkg/reg/util/pattern\.go
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: common/api/base\.go
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: server/middleware/util/util\.go
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
    goimports:
      local-prefixes:
        - github.com/goharbor/harbor
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - .*_test\.go
      - .*test\.go
      - testing
      - src/jobservice/mgt/mock_manager.go
