name: Trivy Nightly Scan
on:
  schedule:
    - cron: '0 2 * * 1-5' # run at 2 AM UTC Monday through Friday
  push:
    branches:
      - next
  workflow_dispatch: # Allow manual triggers


jobs:
  nightly-scan:
    name: Trivy Repository Scan
    permissions:
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Run Trivy scanner on repository
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          scanners: 'vuln,secret,misconfig'
          severity: 'CRITICAL,HIGH,MEDIUM'
          format: 'sarif'
          output: 'trivy-results.sarif'
          skip-dirs: 'node_modules,vendor'
        env:
          # Use AWS' ECR mirror for the trivy-db image, as GitHub's Container
          # Registry is returning a TOOMANYREQUESTS error.
          # Ref: https://github.com/aquasecurity/trivy-action/issues/389
          TRIVY_DB_REPOSITORY: 'public.ecr.aws/aquasecurity/trivy-db:2'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
