name: Pull upstream changes
on:
  schedule:
    # Run every 5 minutes for testing
    - cron:  '*/5 * * * *'
    # Run every day at 00:00 UTC
    # - cron:  '0 0 * * *'
  pull_request:
    branches:
      - next


jobs:
  release_pull_request:
    permissions:
      # permission to write to a branch
      contents: write
      # permission to create a pull request
      pull-requests: write
      # permission to change the workflow folder contents
      actions: write
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
    - name: checkout
    - name: checkout
      uses: actions/checkout@v6
    - name: Create PR to branch
      uses: gorillio/github-action-sync@master
      with:
        upstream: https://github.com/goharbor/harbor.git
        upstream_branch: main
        branch: update-next
        pr_labels: upstream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITBOT_EMAIL: goharbor@goharbor.io
        DRY_RUN: false
